{
 "title": "JVM Overview (OpenTelemetry)",
 "tags": [ "debug" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service_name) (jvm_memory_used_bytes)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "JVM Class Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (jvm_class_count)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service_name) (jvm_thread_count)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Total GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (jvm_gc_duration_seconds_sum)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}