name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build project with Maven
      run: mvn clean install
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the cart Docker image
      run: cd cart-service && docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ecommerce-otel:cart-service
    - name: Docker Push cart
      run: docker push ${{secrets.DOCKER_USER}}/ecommerce-otel:cart-service
    - name: Build the order Docker image
      run: cd order-service && docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ecommerce-otel:order-service
    - name: Docker Push order
      run: docker push ${{secrets.DOCKER_USER}}/ecommerce-otel:order-service
      
